setwd("C:/Workspace/Data")
install.packages("tseries")
install.packages("forecast")
library(tseries)
library(forecast)
data("AirPassengers")
AirPassengers
class(AirPassengers)
plot(AirPassengers
abline(reg=lm(AirPassengers~time(AirPassengers)))
kpss.test(AirPassengers)
plot(log(AirPassengers))
plot(diff(log(AirPassengers)))
abline(h=0)
kpss.test(diff(log(AirPassengers)))
data("airmiles")
airmiles
plot(airmiles)
abline(reg=lm(airmiles~time(airmiles)))
kpss.test(airmiles)
plot(diff(airmiles))
plot(diff(sin(airmiles)))
abline(h=0)
kpss.test(diff(sin(airmiles)))
data("nhtemp")
nhtemp
plot(nhtemp)
kpss.test(nhtemp)
plot(diff(diff(nhtemp))
kpss.test(diff(nhtemp))
adf.test(diff(nhtemp))
6/50
5/40
install.packages("tm")
